

# Heading

## Sub-heading

### Another deeper heading
 
Paragraphs are separated
by a blank line.

Two spaces at the end of a line leave a  
line break.

Text attributes _italic_, *italic*, __bold__, **bold**, `monospace`.

Horizontal rule:

---

Bullet list:

  * apples
  * oranges
  * pears

Numbered list:

  1. apples
  2. oranges
  3. pears

A [link](http://example.com).

In [ ]:
 def maxSequence(a):
    ...:      b,c=[],[]
    ...:      for i in range(len(a)):
    ...:          for j in range(1,len(a)+1-i):
    ...:                b.append( a[i:i+j])
    ...:      for k in b:
    ...:          c.append(sum(k))
    ...:      d=max(c)
    ...:      e=c.index(d)
    ...:      return b[e]
    ...:      
http://www.jianshu.com/p/20afa593c4d3

In [ ]:

In [42]: b.fromkeys(a).keys()
Out[42]: dict_keys([1, 2, 3, 5, 55, 88, 77])

In [43]: a
Out[43]: [1, 2, 3, 5, 5, 88, 77, 55, 2, 88]

In [44]: sorted(a,key=a.index)
Out[44]: [1, 2, 2, 3, 5, 5, 88, 88, 77, 55]

In [45]: sorted(set(a),key=a.index)
Out[45]: [1, 2, 3, 5, 88, 77, 55]

In [46]: 


In [ ]:
sorted(set(a),key=attrgetter('index')(a))

In [ ]:
函数,形参,实参,变量,全局变量,局部变量,作用域,命名空间

In [ ]:

In [15]: a=[3,9,8,5,2]

In [16]: b=[1,4,9,2,6]

In [17]: c=zip(a,b)

In [18]: reduce(lambda z,(x,y): z+x*y,c,0)
Out[18]: 133

In [19]: c
Out[19]: [(3, 1), (9, 4), (8, 9), (5, 2), (2, 6)]


In [ ]:

In [12]: def test2(x,*arg):
    ...:     print x
    ...:     print arg
    ...:     

In [13]: test2(1,2,3,3,4)
1
(2, 3, 3, 4)

In [14]: test2(1,(2,3,3,4))
1
((2, 3, 3, 4),)

In [15]: test2(1,*(2,3,3,4))
1
(2, 3, 3, 4)

In [16]: test2(1,2)
1
(2,)

In [19]: test2(1,*(2,))
1
(2,)


In [ ]:



In [34]:  def test3(**kargs):
    ...:   print kargs


In [35]: test3(a=1,b=2)
{'a': 1, 'b': 2}

In [36]: c={1:1,2:2}

In [37]: test3(**c)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-8d03e7922bda> in <module>()
----> 1 test3(**c)

TypeError: test3() keywords must be strings

In [38]: d={'a':1,'b':2}

In [39]: test3(**d)
{'a': 1, 'b': 2}


In [ ]:
>>> def foo(**args):    #这种方式接收，以 dictionary 的形式接收数据对象
...     print args
... 

>>> foo(1,2,3)          #这样就报错了
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo() takes exactly 0 arguments (3 given)

>>> foo(a=1,b=2,c=3)    #这样就可以了，因为有了键值对
{'a': 1, 'c': 3, 'b': 2}
下面来一个综合的，看看以上四种参数传递方法的执行顺序

>>> def foo(x,y=2,*targs,**dargs):
...     print "x==>",x
...     print "y==>",y
...     print "targs_tuple==>",targs
...     print "dargs_dict==>",dargs
... 

>>> foo("1x")
x==> 1x
y==> 2
targs_tuple==> ()
dargs_dict==> {}

>>> foo("1x","2y")
x==> 1x
y==> 2y
targs_tuple==> ()
dargs_dict==> {}

>>> foo("1x","2y","3t1","3t2")
x==> 1x
y==> 2y
targs_tuple==> ('3t1', '3t2')
dargs_dict==> {}

>>> foo("1x","2y","3t1","3t2",d1="4d1",d2="4d2")
x==> 1x
y==> 2y
targs_tuple==> ('3t1', '3t2')
dargs_dict==> {'d2': '4d2', 'd1': '4d1'}

In [ ]:
In [10]: def test1(n):
    ...:     if n==0:
    ...:         return 0
    ...:     else:
    ...:         return test1(n-2)+n
    ...:         
    ...:         
    ...:         
    ...:     

In [11]: test1(10)
Out[11]: 30

In [12]: test1(2)
Out[12]: 2

In [13]: sum([x for x in range(11) if x%2==0])
Out[13]: 30


In [ ]:
In [7]: map(add,[1,2,3,4],[1,2,3,4])
Out[7]: [2, 4, 6, 8]
    
    
In [34]: reduce(add,[1,2,3,4])
Out[34]: 10

    

In [8]: map(lambda x,y:x+y,[1,2,3,4],[1,2,3,4])
Out[8]: [2, 4, 6, 8]


In [10]: [ x+y for x in [1,2,3,4]  for y in [1,2,3,4]]
Out[10]: [2, 3, 4, 5, 3, 4, 5, 6, 4, 5, 6, 7, 5, 6, 7, 8]
    
    

In [ ]:
In [11]: b=numpy.array([2,3,3,4])

In [12]: a+b
Out[12]: array([3, 5, 6, 8])

In [13]: a
Out[13]: array([1, 2, 3, 4])

In [14]: b
Out[14]: array([2, 3, 3, 4])

In [15]: from operator import *

In [16]: reduce(add,(a,b))
Out[16]: array([3, 5, 6, 8])

In [17]: map(add,a,b)
Out[17]: [3, 5, 6, 8]


In [ ]:
>>> a
[3, 9, 8, 5, 2]
>>> b
[1, 4, 9, 2, 6]

>>> zip(a,b)        #复习一下 zip，下面的方法中要用到
[(3, 1), (9, 4), (8, 9), (5, 2), (2, 6)]

>>> sum(x*y for x,y in zip(a,b))    #解析后直接求和
133

>>> new_list = [x*y for x,y in zip(a,b)]    #可以看做是上面方法的分布实施

>>> #这样解析也可以：new_tuple = (x*y for x,y in zip(a,b))
>>> new_list
[3, 36, 72, 10, 12]
>>> sum(new_list)     #或者:sum(new_tuple)
133

>>> reduce(lambda sum,(x,y): sum+x*y,zip(a,b),0)    #这个方法是在耍酷呢吗？
133

>>> from operator import add,mul            #耍酷的方法也不止一个
>>> reduce(add,map(mul,a,b))
133

>>> reduce(lambda x,y: x+y, map(lambda x,y: x*y, a,b))  #map,reduce,lambda 都齐全了，更酷吗？
133

In [19]:
def is_prime(n):
    if n<=1:
        return False
    elif  not isinstance(n,int):
        return False
    elif 0 not in [n%x for x in range(2,n)]:
        return True   
    else:
        return False

In [20]:
is_prime(2)

True

In [21]:
is_prime(1)

False

In [22]:
is_prime(4)

False

In [23]:
is_prime(11)

True

In [24]:
is_prime(11.1)

False

In [25]:
is_prime('dd')

False

In [ ]:
python2.7

In [ ]:
旧式类

In [ ]:

In [1]: class AA:
   ...:     pass
   ...: 

In [2]: aa=AA()

In [3]: type(aa)
Out[3]: instance

In [4]: type(AA)
Out[4]: classobj

In [5]: aa.__class__
Out[5]: <class __main__.AA at 0x7f102232ece8>


  




In [ ]:
新式类

In [ ]:

In [7]: class BB(object):
   ...:     pass
   ...: 

In [8]: bb=BB()

In [9]: type(bb)
Out[9]: __main__.BB

In [10]: type(BB)
Out[10]: type



In [12]: bb.__class__
Out[12]: __main__.BB

In [ ]:
>>> __metaclass__ = type
>>> class CC:
...     pass
... 
>>> cc = CC()
>>> cc.__class__
<class '__main__.CC'>
>>> type(cc)
<class '__main__.CC'>

In [ ]:
python3.5

In [ ]:

In [1]: class AA:
   ...:     pass                       |         
   ...: 

In [2]: aa=AA()

In [3]: type(aa)                                 
Out[3]: __main__.AA

In [4]: type(AA)
Out[4]: type

In [5]: aa.__class__
Out[5]: __main__.AA




In [ ]:

In [1]: class BB(object):
   ...:     pass
   ...: 

In [2]: bb=BB()

In [4]: type(bb)
Out[4]: __main__.BB

In [5]: type(BB)
Out[5]: type

In [6]: bb.__class__
Out[6]: __main__.BB


# A

***
## B

***
### C





In [ ]:
List

* a
* b
* c

- a
- b
- c

3. Bird
1. McHale
8. Parish

In [ ]:
Picture

![](http://stimg0.tuicool.com/QNviIn.png)

In [ ]:
Quote


> Donec sit amet nisl. Aliquam semper ipsum sit amet velit.
    Suspendisse id sem consectetuer libero luctus adipiscing.


In [ ]:
换行:空格+空格+回车

ABVD   
FEFFFF   


> 这是一级引用
>>这是二级引用
>>> 这是三级引用


```javascript
var canvas = document.getElementById("canvas");
var context = canvas.getContext("2d");
```

|         序号    |    交易名    |    交易说明    |    备注    |
|    ------: |    :-------:    |    :---------   |    ------    |
|    1    |    prfcfg    |    菜单配置    |    可以通过此交易查询到所有交易码和菜单的对应关系    |
|    2    |    gentmo    |    编译所有交易    |    |
|    100000    |    sysdba    |    数据库表模型汇总    |    |

~~这是一条删除线~~

https://www.zybuluo.com/AntLog/note/63228

In [8]:
def createGenerator():
        mylist = range(3)
        for i in mylist:
            yield i*i


In [9]:
a=createGenerator()

In [10]:
next(a)

0

In [11]:
next(a)

1

In [12]:
next(a)

4

In [13]:
next(createGenerator())

0

In [14]:
next(createGenerator())

0

 # 变量名定义在形参,初始化于默认参数


In [22]:

In [24]: def a(n=0):
    ...:     while 1:
    ...:         n+=1
    ...:         yield n
    ...:         
    ...:         
    ...:         
    ...:         



In [16]:
a=a(1)

In [17]:
a

<generator object a at 0x7f9e24721500>

In [18]:
next(a)

2

In [19]:
next(a)

3

In [20]:
next(a)

4

In [21]:
next(a)

5

In [25]:
 def a(L):
        for j in range(len(L)):
            for i in range(len(L) - 1):
                if L[i] > L[i+1]:
                    L[i], L[i+1]=L[i+1], L[i]
        print L


In [31]:
L=[17,2,1,0.5,5,3,8,2]

In [32]:
a(L)

[0.5, 1, 2, 2, 3, 5, 8, 17]


In [34]:
a=[]
for i in range(5):
    for j in range(5):
        a.append((i,j))
        

In [35]:
a

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (4, 0),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4)]

In [36]:
len(a)

25

In [ ]:
In [19]: def jiecheng(n):
    ...:     if n==1:
    ...:         b=1
    ...:     else:
    ...:         b= n*jiecheng(n-1)
    ...:     return  b


In [ ]:

In [12]: a=1

In [13]: for i in range(1,10):
    ...:     c=a*i
    ...:     print ('{}*{}={}'.format(a,i,c))
    ...:     a=c
    ...:     
    ...:     
    ...:     
    ...:     
    ...:     
1*1=1
1*2=2
2*3=6
6*4=24
24*5=120
120*6=720
720*7=5040
5040*8=40320
40320*9=362880


In [ ]:
In [53]: def fun2(n):
    ...:     a=0
    ...:     for i in range(5,n+5,5):
    ...:         j=i
    ...:         while 1:
    ...:           if  j%5==0:
    ...:               a+=1
    ...:               j/=5
    ...:           else:
    ...:               break
    ...:     return a
    ...:     
    ...:           
    ...:     

In [54]: fun2(10)
Out[54]: 2
    
   






In [55]: def fun2(n):
    ...:     a=0
    ...:     while n:
    ...:         a+=n//5
    ...:         n//=5
    ...:     return a
    ...: 

In [56]: fun2(10)
Out[56]: 2

In [57]: fun2(5)
Out[57]: 1

In [58]: fun2(1000)
Out[58]: 249


    
    
    
    
    
    
    
http://www.programgo.com/article/11822812666/

In [ ]:
In [70]: def fun2(n):
    ...:     a=0
    ...:     i=1
    ...:     while n:
    ...:         if 5**i > n:
    ...:             break
    ...:         a+=n//(5**i)
    ...:         i+=1
    ...:       
    ...:     return a
    
    
    ...: 
比如求1到100的数因式分解中有多少个5，可以知道5的倍数有20个，25的倍数有4个，所以一共有24个5。
Z=N/5 + N/(5^2) + N/(5^3)+.
